---
- name: Install Syncthing
  hosts: localhost
  become: yes

  tasks:
    - name: Install syncthing package
      dnf:
        name:
          - syncthing
        state: present

    - name: Enable and start syncthing service for user not root
    # sudo systemctl enable --now syncthing@[[USER_NOT_ROOT]].service
      systemd:
        name: "syncthing@{{ lookup('env', 'SUDO_USER') }}.service"
        enabled: yes
        state: started