---
- name: Install Visual Studio Code
  hosts: localhost
  become: yes

  tasks:
    - name: Import Microsoft GPG key
      rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Visual Studio Code repository
      copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          autorefresh=1
          type=rpm-md
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc

    - name: Install Visual Studio Code
      dnf:
        name: code
        state: present
