---
- name: Install Bluetooth codecs
  hosts: localhost
  become: yes

  tasks:
    - name: Install additional Bluetooth codec packages
      dnf:
        name:
          - libfreeaptx
          - libldac
          - fdk-aac
        state: present